[tool.poetry]
name = "stalactite"
version = "0.1.0"
description = "\"A Framework for Vertical Federated Learning\""
authors = ["fonhorst <fonhorst@alipoov.nb@gmail.com>"]
readme = "README.md"
packages = [
    { include = "stalactite" }
]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.1.1"
grpcio = "^1.59.3"
safetensors = "^0.4.0"
numpy = "^1.26.2"


[tool.poetry.group.dev.dependencies]
grpcio-tools = "^1.59.3"
prometheus-client = "^0.19.0"
prometheus-async = "^22.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
