version: '3.9'
name: mlflow

services:
  mlflow-vfl:
    image: anastasiiazakharova/mlflow-server:2.3
    command:
      - "--backend-store-uri"
      - 'postgresql+psycopg2://mlflow:mlflow@postgres-vfl:5432/mlflow'
      - "--default-artifact-root"
      - "/var/lib/mlruns"
      - "--host"
      - "0.0.0.0"
    volumes:
      - mlruns:/var/lib/mlruns
    ports:
      - ${MLFLOW_PORT}:5000
    networks:
      - vfl-network

  postgres-vfl:
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_USER=mlflow
      - POSTGRES_DB=mlflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vfl-network

networks:
  vfl-network:
    external: true

volumes:
  postgres_data:
  mlruns:
