# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stalactite.communications.grpc_utils.generated_code.arbitered_communicator_pb2 as arbitered__communicator__pb2


class ArbiteredCommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendToArbiter = channel.unary_unary(
                '/ArbiteredCommunicator/SendToArbiter',
                request_serializer=arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
                response_deserializer=arbitered__communicator__pb2.MainArbiterMessage.FromString,
                )
        self.RecvFromArbiter = channel.unary_unary(
                '/ArbiteredCommunicator/RecvFromArbiter',
                request_serializer=arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
                response_deserializer=arbitered__communicator__pb2.MainArbiterMessage.FromString,
                )
        self.CheckIfAvailable = channel.unary_unary(
                '/ArbiteredCommunicator/CheckIfAvailable',
                request_serializer=arbitered__communicator__pb2.IsReady.SerializeToString,
                response_deserializer=arbitered__communicator__pb2.IsReady.FromString,
                )


class ArbiteredCommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendToArbiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecvFromArbiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIfAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArbiteredCommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendToArbiter': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToArbiter,
                    request_deserializer=arbitered__communicator__pb2.MainArbiterMessage.FromString,
                    response_serializer=arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
            ),
            'RecvFromArbiter': grpc.unary_unary_rpc_method_handler(
                    servicer.RecvFromArbiter,
                    request_deserializer=arbitered__communicator__pb2.MainArbiterMessage.FromString,
                    response_serializer=arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
            ),
            'CheckIfAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIfAvailable,
                    request_deserializer=arbitered__communicator__pb2.IsReady.FromString,
                    response_serializer=arbitered__communicator__pb2.IsReady.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArbiteredCommunicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArbiteredCommunicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendToArbiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArbiteredCommunicator/SendToArbiter',
            arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
            arbitered__communicator__pb2.MainArbiterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecvFromArbiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArbiteredCommunicator/RecvFromArbiter',
            arbitered__communicator__pb2.MainArbiterMessage.SerializeToString,
            arbitered__communicator__pb2.MainArbiterMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckIfAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArbiteredCommunicator/CheckIfAvailable',
            arbitered__communicator__pb2.IsReady.SerializeToString,
            arbitered__communicator__pb2.IsReady.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
