# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arbiter.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarbiter.proto\"v\n\x0fRequestResponse\x12\x11\n\tmaster_id\x18\x01 \x01(\t\x12\x1d\n\x10request_response\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x13\n\x11_request_responseB\x08\n\x06_error\"`\n\rPublicContext\x12\x11\n\tmaster_id\x18\x01 \x01(\t\x12\x13\n\x06pubkey\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_pubkeyB\x08\n\x06_error\"\xb6\x01\n\x0b\x44\x61taMessage\x12\x11\n\tmaster_id\x18\x01 \x01(\t\x12\x1b\n\x0e\x65ncrypted_data\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x1d\n\x10\x64\x65\x63rypted_tensor\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x12\n\ndata_shape\x18\x05 \x03(\x05\x42\x11\n\x0f_encrypted_dataB\x13\n\x11_decrypted_tensorB\x08\n\x06_error2\xa2\x01\n\x07\x41rbiter\x12-\n\rDecodeMessage\x12\x0c.DataMessage\x1a\x0c.DataMessage\"\x00\x12\x32\n\x0cGetPublicKey\x12\x10.RequestResponse\x1a\x0e.PublicContext\"\x00\x12\x34\n\x0cGenerateKeys\x12\x10.RequestResponse\x1a\x10.RequestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arbiter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTRESPONSE']._serialized_start=17
  _globals['_REQUESTRESPONSE']._serialized_end=135
  _globals['_PUBLICCONTEXT']._serialized_start=137
  _globals['_PUBLICCONTEXT']._serialized_end=233
  _globals['_DATAMESSAGE']._serialized_start=236
  _globals['_DATAMESSAGE']._serialized_end=418
  _globals['_ARBITER']._serialized_start=421
  _globals['_ARBITER']._serialized_end=583
# @@protoc_insertion_point(module_scope)
