# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arbitered_communicator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61rbitered_communicator.proto\"G\n\x07IsReady\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\r\n\x05ready\x18\x02 \x01(\x08\x12\x11\n\x04role\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_role\"\x92\x03\n\x12MainArbiterMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x07task_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bmethod_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12<\n\rtensor_kwargs\x18\x04 \x03(\x0b\x32%.MainArbiterMessage.TensorKwargsEntry\x12:\n\x0cother_kwargs\x18\x05 \x03(\x0b\x32$.MainArbiterMessage.OtherKwargsEntry\x12!\n\x14get_response_timeout\x18\x07 \x01(\x02H\x02\x88\x01\x01\x1a\x33\n\x11TensorKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a\x32\n\x10OtherKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\n\n\x08_task_idB\x0e\n\x0c_method_nameB\x17\n\x15_get_response_timeout2\xbd\x01\n\x15\x41rbiteredCommunicator\x12;\n\rSendToArbiter\x12\x13.MainArbiterMessage\x1a\x13.MainArbiterMessage\"\x00\x12=\n\x0fRecvFromArbiter\x12\x13.MainArbiterMessage\x1a\x13.MainArbiterMessage\"\x00\x12(\n\x10\x43heckIfAvailable\x12\x08.IsReady\x1a\x08.IsReady\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arbitered_communicator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAINARBITERMESSAGE_TENSORKWARGSENTRY']._options = None
  _globals['_MAINARBITERMESSAGE_TENSORKWARGSENTRY']._serialized_options = b'8\001'
  _globals['_MAINARBITERMESSAGE_OTHERKWARGSENTRY']._options = None
  _globals['_MAINARBITERMESSAGE_OTHERKWARGSENTRY']._serialized_options = b'8\001'
  _globals['_ISREADY']._serialized_start=32
  _globals['_ISREADY']._serialized_end=103
  _globals['_MAINARBITERMESSAGE']._serialized_start=106
  _globals['_MAINARBITERMESSAGE']._serialized_end=508
  _globals['_MAINARBITERMESSAGE_TENSORKWARGSENTRY']._serialized_start=352
  _globals['_MAINARBITERMESSAGE_TENSORKWARGSENTRY']._serialized_end=403
  _globals['_MAINARBITERMESSAGE_OTHERKWARGSENTRY']._serialized_start=405
  _globals['_MAINARBITERMESSAGE_OTHERKWARGSENTRY']._serialized_end=455
  _globals['_ARBITEREDCOMMUNICATOR']._serialized_start=511
  _globals['_ARBITEREDCOMMUNICATOR']._serialized_end=700
# @@protoc_insertion_point(module_scope)
