global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: master-agent
    static_configs:
    - targets:
      - "master-agent-vfl:8765"
      - "master-agent-vfl-test:8765"
      - "master-agent-vfl-distributed:8765"
      - "master-agent-vfl-distributed-predict:8765"
