{
 "title": "VFL experiment dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Iteration time, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "iteration_time_gauge", "legendFormat": "{{run_id}}" }
   ]
  },
  {
   "title": "Iteration time, sec",
   "type": "bargauge",
   "description": "Histogram of iteration time distribution on master",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iteration_time_hist_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Task execution time (records_uids)",
   "type": "bargauge",
   "description": "To check other task types, go to the `Query-builder` -> `Label filters` and change the `task_type` to desired task type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (agent_task_execution_time_bucket{task_type=\"records_uids\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Task execution time (predict_partial)",
   "type": "bargauge",
   "description": "To check other task types, go to the `Query-builder` -> `Label filters` and change the `task_type` to desired task type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (agent_task_execution_time_bucket{task_type=\"predict_partial\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Received messages on master",
   "type": "stat",
   "description": "You can change the message sender id to see the stats for it by going to the Query-Builder -> Label filters and choosing another client_id value",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task_message_size_count{client_id=\"member-0\"}",
     "legendFormat": "{{run_id}} {{experiment_label}} {{task_type}}"
    }
   ]
  },
  {
   "title": "Member send time (.95Q - predict)",
   "type": "stat",
   "description": ".95 quantile\n\nTo check other task types, go to the Query-builder -> Label filters and change the task_type to desired task type\nTo see other quantiles values, change the `Histogram quantile` at the Operations section to desired value.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(member_send_time_bucket{task_type=\"predict\"}[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Received message size (predict_partial)",
   "type": "heatmap",
   "description": "To check other task types, go to the Query-builder -> Label filters and change the task_type to desired task type",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "task_message_size_bucket{task_type=\"predict_partial\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of connected members",
   "type": "stat",
   "description": "Number of the members sending pings to master",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_connected_agents",
     "legendFormat": "{{run_id}} {{experiment_label}}"
    }
   ]
  }
 ]
}