# This config is not meant to be changed (except for empty fields) as it is used in tests.
# Set directories paths before running tests. For experiments, copy the file contents into `config.yml`

common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  experiment_label: test-experiment-0
  reports_export_folder: "." # todo: Path to export tests logs and reports
  rendezvous_timeout: 360
  world_size: 2

vfl_model:
  epochs: 1
  batch_size: 1000
  vfl_model_name: linreg
  is_consequently: False
  learning_rate: 0.2
  use_class_weights: False


prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'
  prometheus_host: 'node3.bdcl'
  prometheus_port: '9090'
  grafana_port: '3001'

data:
  random_seed: 0
  dataset_size: 1000
  host_path_data_dir: "." # todo: Path to directory containing pickled datasets
  dataset: 'mnist'
  use_smm: False
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"

grpc_server:
  host: '0.0.0.0'
  port: '50051'
  max_message_size: -1
  server_threadpool_max_workers: 10

master:
  container_host: 0.0.0.0
  run_mlflow: True
  run_prometheus: True
  logging_level: 'debug'
  disconnect_idle_client_time: 120.
  recv_timeout: 360
  time_between_idle_connections_checks: 3

member:
  logging_level: 'debug'
  heartbeat_interval: 2.
  recv_timeout: 360
  sent_task_timout: 3600


grpc_arbiter:
  container_host: 'node3.bdcl'
  host: '0.0.0.0'
  port: '50052'
  max_message_size: -1
  server_threadpool_max_workers: 10
  use_arbiter: True
  ts_algorithm: CKKS
  ts_poly_modulus_degree: 8192
  ts_coeff_mod_bit_sizes:
    - 60
    - 40
    - 40
    - 60
  ts_global_scale_pow: 20
  ts_generate_relin_keys: True
  ts_generate_galois_keys: True
#  ts_context_path: "." # todo: Path to file with serialized Tenseal context

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: "." # todo: Path to the docker-compose.yml file and prerequisites configs/
  use_gpu: False
