common:
  epochs: 5
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 1000
  experiment_label: experiment-vm
  reports_export_folder: "/Users/anastasiazaharova/Desktop/vfl-benchmark/reports"
#  vfl_model_name: linreg
  vfl_model_name: logreg
  is_consequently: False
  learning_rate: 0.01
  use_class_weights: False


data:
  random_seed: 0
  dataset_size: 1000
#  host_path_data_dir: "/mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/data"
#  dataset: 'mnist'
#  use_smm: False
  dataset: 'sbol'
  use_smm: True
