common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 1
  experiment_label: sbol-smm-logreg-multi-multiprocess-no-features-master
  reports_export_folder: "../../reports"

vfl_model:
  epochs: 10
  batch_size: 8500
  vfl_model_name: logreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.05
#  l2_alpha: 0.2
  do_train: True
  do_predict: False
  do_save_model: False
  vfl_model_path: ../../saved_models/logreg_model_arbitered_he

prerequisites:
  mlflow_host: '0.0.0.0'
  mlflow_port: '5555'

master:
  external_host: '0.0.0.0'
  run_mlflow: True
  recv_timeout: 3600.

member:
  recv_timeout: 3600.


data:
  dataset_size: 10000
  dataset: 'sbol_master_only_labels'
  host_path_data_dir:  ../../data/sber_ds_vfl/multilabel_sber_samplemaster_no_labels_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"
  num_classes: 19

grpc_arbiter:
  use_arbiter: True
  recv_timeout: 3600.

docker:
  docker_compose_command: docker compose
  docker_compose_path: "../../prerequisites"
  use_gpu: True