common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 1
  experiment_label: he-sbol-smm-logreg-multi
  reports_export_folder: "../../reports"

vfl_model:
  epochs: 10
  batch_size: 8500
  vfl_model_name: logreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.05
  l2_alpha: 0.2
  do_train: True
  do_predict: False
  do_save_model: True
  vfl_model_path: ../../saved_models/logreg_model_arbitered_he

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'

master:
  external_host: 'node3.bdcl'
  run_mlflow: True

data:
  dataset_size: 10000
  dataset: 'sbol_smm'
  host_path_data_dir: ../../data/sber_ds_vfl/vfl_multilabel_sber_sample10000_smm_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"
  num_classes: 19

grpc_arbiter:
  use_arbiter: True
  security_protocol_params:
    he_type: paillier
    key_length: 128
    n_threads: 20
    encryption_precision: 1e-10
    encoding_precision: 1e-10