common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-efficientnet-mnist-local
  reports_export_folder: "/Users/alexgrig/stalactite_data/reports"

vfl_model:
  epochs: 1
  batch_size: 250
  eval_batch_size: 200
  vfl_model_name: efficientnet
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.01
  do_train: True
  do_predict: False
  do_save_model: False
  vfl_model_path: /Users/alexgrig/stalactite_data/models/efficientnet_model

prerequisites:
  mlflow_host: localhost
  mlflow_port: "9876"
  prometheus_host: localhost
  prometheus_port: "9090"
  grafana_port: "3000"

master:
  #container_host: 'node16.bdcl'
  run_mlflow: True
  run_prometheus: True
  master_model_params: {
    input_dim: 128,
    dropout: 0.2,
    num_classes: 10,
#    init_weights: 0.005
  }
  recv_timeout: 360

member:
  member_model_params: {
   width_mult: 0.1,
   depth_mult: 0.1,
#    init_weights: 0.005
  }

data:
  random_seed: 0
  dataset_size: 750
  dataset: 'mnist'
  use_smm: False
  host_path_data_dir:  /Users/alexgrig/stalactite_data/mnist_binary38_parts_2
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"
  uids_key: "image_idx"


docker:
  docker_compose_path: "../../prerequisites"
  docker_compose_command: "docker compose"
  use_gpu: False