common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: test-experiment-mnist-local
  reports_export_folder: ../../reports
  seed: 22

vfl_model:
  epochs: 2
  batch_size: 5000
  eval_batch_size: 200
  vfl_model_name: linreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.2
  do_train: True
  do_predict: True
  do_save_model: True
  vfl_model_path: ../../saved_models/linreg_model

data:
  dataset_size: 5000
  dataset: 'mnist'
  host_path_data_dir: ../../data/sber_ds_vfl/mnist_vfl_parts2
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"
  uids_key: "image_idx"

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'

master:
  external_host: 'node3.bdcl'
  run_prometheus: False
  port: "50051"
  logging_level: 'debug'
  disconnect_idle_client_time: 500.
  recv_timeout: 3600.
  cuda_visible_devices: "0"

member:
  member_model_params: {
    output_dim: 1,
    reg_lambda: 0.5
  }
  heartbeat_interval: 2.
  logging_level: 'info'
  recv_timeout: 3600.

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: '../../prerequisites'
  use_gpu: True