common:
  experiment_label: experiment-vm
  reports_export_folder: "/mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/reports"
  epochs: 5
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 1000
  vfl_model_name: linreg
  is_consequently: False
  learning_rate: 0.01
  use_class_weights: False


prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'
  prometheus_host: 'node3.bdcl'
  prometheus_port: '9090'
  grafana_port: '3001'

data:
  random_seed: 0
  dataset_size: 1000
  host_path_data_dir: /mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/data/sber_ds_vfl/mnist_binary38_parts2 # /home/dmitriy/data #
  dataset: 'mnist'
  use_smm: False
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"

grpc_server:
  host: '0.0.0.0'
  port: '50051'
  max_message_size: -1
  #  server_threadpool_max_workers: 10


master:
  container_host: 'node3.bdcl'
  run_mlflow: True
  run_prometheus: True
  logging_level: 'debug'
  disconnect_idle_client_time: 120.
  #  time_between_idle_connections_checks: 3
  #  recv_timeout: 360

member:
  logging_level: 'debug'
  heartbeat_interval: 2.
  #  heartbeat_interval: 2
  #  sent_task_timout: 3600

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: '/mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/prerequisites'
  use_gpu: False


#grpc_arbiter:
#  use_arbiter: False





