common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-mnist-sequential-local
  reports_export_folder: ../../reports

vfl_model:
  epochs: 6
  batch_size: 5000
  eval_batch_size: 200
  vfl_model_name: linreg
  is_consequently: True
  use_class_weights: False
  learning_rate: 0.02
  do_train: True
  do_predict: True
  do_save_model: True
  vfl_model_path: ../../saved_models/linreg_model_seq

data:
  random_seed: 0
  dataset_size: 5000
  dataset: 'mnist'
  host_path_data_dir: ../../data/sber_ds_vfl/mnist_binary38_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "image_part_"
  label_key: "label"

prerequisites:
  mlflow_host: node3.bdcl
  mlflow_port: "5555"

master:
  run_mlflow: False

member:
  member_model_params: {
    output_dim: 1,
    reg_lambda: 0.5
  }