common:
  epochs: 6
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 5000
  experiment_label: experiment-mnist-sequential-local
  reports_export_folder: ../../reports
  vfl_model_name: linreg
  is_consequently: True
  learning_rate: 0.02
  use_class_weights: False


data:
  random_seed: 0
  dataset_size: 5000
  dataset: 'mnist'
  use_smm: False
  host_path_data_dir: ../../data/sber_ds_vfl/mnist_binary38_parts2
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"


prerequisites:
  mlflow_host: node3.bdcl
  mlflow_port: "5555"

master:
  run_mlflow: False