common:
  epochs: 2
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 5000
  experiment_label: experiment-mnist-centralized
  reports_export_folder: "/Users/anastasiazaharova/Desktop/vfl-benchmark/reports"  #
  vfl_model_name: linreg
  is_consequently: False
  learning_rate: 0.2
  use_class_weights: False
#  random_seed: 0 # TODO

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'

master:
  container_host: 'node3.bdcl'
  run_mlflow: True

data:
  random_seed: 0
  dataset_size: 5000 #000
  dataset: 'mnist'
  use_smm: False
  host_path_data_dir:  /Users/anastasiazaharova/Desktop/vfl-benchmark/data/sber_ds_vfl/mnist_single
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"
