common:
  epochs: 5
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 1000
  experiment_label: experiment-mnist
  reports_export_folder: "/Users/anastasiazaharova/Desktop/vfl-benchmark/reports" # "/home/dmitriy/data/reports" #
  vfl_model_name: linreg
  is_consequently: True
  learning_rate: 0.01
  use_class_weights: False
#  random_seed: 0 # TODO


data:
  random_seed: 0
  dataset_size: 1000
  dataset: 'mnist'
  use_smm: False
  host_path_data_dir: "/Users/anastasiazaharova/Desktop/vfl-benchmark/data/sber_ds_vfl/mnist_binary38_parts2"  #/Users/anastasiazaharova/Desktop/vfl-benchmark/data/sber_ds_vfl #  #
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "image_part_"
  label_key: "label"
