common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-mnist-sequential-local
  reports_export_folder: /Users/alexgrig/stalactite_data/reports

vfl_model:
  epochs: 2
  batch_size: 5000
  eval_batch_size: 200
  vfl_model_name: linreg
  is_consequently: True
  use_class_weights: False
  learning_rate: 0.02
  do_train: True
  do_predict: True
  do_save_model: True
  vfl_model_path: /Users/alexgrig/stalactite_data/models/linreg_model_seq

data:
  random_seed: 0
  dataset_size: 5000
  dataset: 'mnist'
  use_smm: False
  host_path_data_dir: /Users/alexgrig/stalactite_data/mnist_binary38_parts_2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "image_part_"
  label_key: "label"
  uids_key: "image_idx"

prerequisites:
  mlflow_host: localhost
  mlflow_port: "9876"
  prometheus_host: localhost
  prometheus_port: "9090"
  grafana_port: "3000"

master:
  run_mlflow: True
  logging_level: debug
  #container_host: 0.0.0.0
  run_prometheus: True
  #disconnect_idle_client_time: 120
  #time_between_idle_connections_checks: 3
  recv_timeout: 360

member:
  member_model_params: {
    output_dim: 1,
    reg_lambda: 0.5
  }

  logging_level: debug
  recv_timeout: 360


docker:
  docker_compose_path: "../../prerequisites"
  docker_compose_command: "docker compose"
  use_gpu: False