common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: test-experiment-mnist-local
  reports_export_folder: /home/user1/stalactite_data/reports #../../reports
  seed: 42

vfl_model:
  epochs: 2
  batch_size: 1000
  eval_batch_size: 200
  vfl_model_name: linreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.2
  do_train: True
  do_predict: True
  do_save_model: True
  vfl_model_path: /Users/alexgrig/stalactite_data/models/linreg_model_local #../../saved_models/linreg_model

data:
  random_seed: 0
  dataset_size: 5000
  dataset: 'mnist'
#  host_path_data_dir:  ../../data/sber_ds_vfl/mnist_binary38_parts2
  host_path_data_dir:  /Users/alexgrig/stalactite_data/mnist_binary38_parts_3 #../../data/sber_ds_vfl/mnist_test
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "image_part_"
  label_key: "label"
  uids_key: "image_idx"

prerequisites:
  mlflow_host: 176.123.161.62 # 0.0.0.0
  mlflow_port: "5555"
  prometheus_host: 0.0.0.0
  prometheus_port: "9090"
  grafana_port: "3000"

#grpc_server:
#  host: 0.0.0.0
#  port: 50051
#  max_message_size: -1
#  server_threadpool_max_workers: 10

#grpc_arbiter:
#  use_arbiter: False

master:
  run_mlflow: True
  logging_level: debug
  external_host: 0.0.0.0
  run_prometheus: True 
  disconnect_idle_client_time: 120
  time_between_idle_connections_checks: 3
  recv_timeout: 360

member:
  member_model_params: {
    output_dim: 1,
    reg_lambda: 0.5
  }
  logging_level: debug
  recv_timeout: 360
  heartbeat_interval: 2
  sent_task_timout: 3600

docker:
  docker_compose_path: "../../prerequisites"
  docker_compose_command: "docker compose"
  use_gpu: False