common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-sbol-smm-local
  reports_export_folder: "../../reports"

vfl_model:
  epochs: 1
  batch_size: 2500
  eval_batch_size: 200
  vfl_model_name: logreg
  is_consequently: False
  use_class_weights: True
  learning_rate: 0.05
  weight_decay: 0.02
  do_train: True
  do_predict: True
  do_save_model: True
  vfl_model_path: ../../saved_models/logreg_model


prerequisites:
  mlflow_host: 'node16.bdcl'
  mlflow_port: '9876'

master:
  external_host: 'node16.bdcl'
  run_mlflow: True

member:
  member_model_params: {
    init_weights: 0.005,
    output_dim: 19,
  }


data:
  random_seed: 0
  dataset_size: 8500
  dataset: 'sbol_smm'
  host_path_data_dir:  ../../data/sber_ds_vfl/multilabel_sber_sample10000_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"
  uids_key: "user_id"