common:
  epochs: 1
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 1
  batch_size: 2500
  experiment_label: experiment-sbol-smm-centralized
  reports_export_folder: "/Users/anastasiazaharova/Desktop/vfl-benchmark/reports" #
  vfl_model_name: logreg
  is_consequently: False
  learning_rate: 0.2
  use_class_weights: True

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'

master:
  container_host: 'node3.bdcl'
  run_mlflow: False

data:
  random_seed: 0
  dataset_size: 8500
  dataset: 'sbol'
  use_smm: True
  host_path_data_dir: /Users/anastasiazaharova/Desktop/vfl-benchmark/data/sber_ds_vfl/vfl_multilabel_sber_sample10000_parts1
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_key: "features_part_"
  label_key: "labels"