common:
  experiment_label: experiment-vm
  reports_export_folder: "/mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/reports"
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2

vfl_model:
  epochs: 5
  batch_size: 1000
  vfl_model_name: logreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.01

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'
  prometheus_host: 'node3.bdcl'
  prometheus_port: '9090'
  grafana_port: '3001'

data:
  random_seed: 0
  dataset_size: 1000
  dataset: 'sbol'
  use_smm: True
  host_path_data_dir: /mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/data/sber_ds_vfl/vfl_multilabel_sber_sample10000_parts2 # /home/dmitriy/data #
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"

grpc_server:
  host: '0.0.0.0'
  port: '50051'
  max_message_size: -1

master:
  container_host: 'node3.bdcl'
  run_mlflow: True
  run_prometheus: True
  logging_level: 'debug'
  disconnect_idle_client_time: 120.

member:
  logging_level: 'debug'
  heartbeat_interval: 2.

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: '/mnt/ess_storage/DN_1/storage/qa-system-research/zakharova/vfl-benchmark-test-mounts/prerequisites'
