common:
  epochs: 5
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  batch_size: 1000
  experiment_label: experiment-vm
  reports_export_folder: "/home/dmitriy/data/reports" #"/Users/anastasiazaharova/Desktop/vfl-benchmark/reports"
  vfl_model_name: logreg
  is_consequently: False
  learning_rate: 0.01
  use_class_weights: False



data:
  random_seed: 0
  dataset_size: 1000
  dataset: 'sbol'
  use_smm: True
  host_path_data_dir: /Users/anastasiazaharova/Desktop/vfl-benchmark/data/sber_ds_vfl/vfl_multilabel_sber_sample10000_parts2 # /home/dmitriy/data #
  dataset_part_prefix: 'part_' # used in dataset folder structure inspection. Concatenated with the index of a party: 0,1,... etc.
  train_split: "train_train" # name of the train split
  test_split: "train_val" # name of the test split
  features_data_preprocessors: [FullDataTensor(features_key),  SkLearnStandardScaler]
  label_data_preprocessors: [FullDataTensor(label_key)]
  features_key: "features_part_"
  label_key: "labels"