common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-vms
  reports_export_folder: "../../reports"
  rendezvous_timeout: 3600

vfl_model:
  epochs: 5
  batch_size: 1000
  vfl_model_name: logreg
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.01

prerequisites:
  mlflow_host: '158.160.110.227'
  mlflow_port: '5555'
  prometheus_host: '158.160.110.227'
  prometheus_port: '9090'
  grafana_port: '3001'

data:
  random_seed: 0
  dataset_size: 1000
  dataset: 'sbol_smm'
  host_path_data_dir: ../../data/sber_ds_vfl/vfl_multilabel_sber_sample10000_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"

grpc_server:
  port: '50051'
  max_message_size: -1
  server_thread_pool_size: 10

master:
  external_host: '158.160.110.227'
  run_mlflow: True
  run_prometheus: True
  logging_level: 'info'
  disconnect_idle_client_time: 120.
  time_between_idle_connections_checks: 3.


member:
  logging_level: 'info'
  heartbeat_interval: 2.
  sent_task_timout: 3600
  member_model_params: {
      output_dim: 19,
    }

grpc_arbiter:
  use_arbiter: False

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: '../../prerequisites'
  use_gpu: False
