common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-mlp-sbol-smm-local
  reports_export_folder: "../../reports"
  seed: 22

vfl_model:
  epochs: 1
  batch_size: 250
  eval_batch_size: 200
  vfl_model_name: mlp
  is_consequently: False
  use_class_weights: True
  learning_rate: 0.01
  do_train: True
  do_predict: False
  do_save_model: False
  vfl_model_path: ../../saved_models/mlp_model


prerequisites:
  mlflow_host: 'node16.bdcl'
  mlflow_port: '9876'

master:
  external_host: 'node16.bdcl'
  run_mlflow: True
  master_model_params: {
    input_dim: 100,
    output_dim: 19,
    multilabel: True,
#    init_weights: 0.005
  }

member:
  member_model_params: {
    hidden_channels:[1000, 300, 100],
#    init_weights: 0.005
  }

data:
  dataset_size: 10000
  dataset: 'sbol_smm'
  host_path_data_dir:  ../../data/sber_ds_vfl/multilabel_sber_sample10000_smm_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"