common:
  report_train_metrics_iteration: 1
  report_test_metrics_iteration: 1
  world_size: 2
  experiment_label: experiment-resnet-sbol-smm-local
  reports_export_folder: "../../reports"

vfl_model:
  epochs: 2
  batch_size: 2500
  eval_batch_size: 2000
  vfl_model_name: resnet
  is_consequently: False
  use_class_weights: False
  learning_rate: 0.01
  do_train: True
  do_predict: False
  do_save_model: True
  vfl_model_path: ../../saved_models/resnet_model

prerequisites:
  mlflow_host: 'node3.bdcl'
  mlflow_port: '5555'

master:
  external_host: 'node3.bdcl'
  run_mlflow: True
  master_model_params: {
    input_dim: 1356,
    output_dim: 19,
    use_bn: True,
  }
  run_prometheus: False
  port: "50051"
  logging_level: 'debug'
  disconnect_idle_client_time: 500.
  recv_timeout: 3600.
  cuda_visible_devices: "0"

member:
  member_model_params: {
    hid_factor: [ 1, 1 ],
  }
  heartbeat_interval: 2.
  logging_level: 'info'
  recv_timeout: 3600.

data:
  dataset_size: 10000
  dataset: 'sbol_smm'
  host_path_data_dir: ../../data/sber_ds_vfl/multilabel_sber_sample10000_smm_parts2
  dataset_part_prefix: 'part_'
  train_split: "train_train"
  test_split: "train_val"
  features_key: "features_part_"
  label_key: "labels"

docker:
  docker_compose_command: "docker compose"
  docker_compose_path: '../../prerequisites'
  use_gpu: True